### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by mooreryan** [lpil/envoy#2]
Hi and thank you for this project!!

I noticed that the repository currently doesn't have a license file.  Could you clarify under what license this project is distributed?  I was thinking of using this package for the cookbook recipe (i.e., https://github.com/gleam-lang/cookbook/issues/15#issuecomment-2368697514).

Thanks again!

**Comment by lpil** [comment]
Hello! The licence for Gleam packages is documented in `gleam.toml`. You can also view licences on Hex: https://hex.pm/packages/envoy
