### ISSUE TITLE
Inconsistent behavior for envoy.get between Erlang and JS targets

### ISSUE THREAD

**Issue by mooreryan** [lpil/envoy#3]
Expected return value according to type annotations is `Result(String, Nil)`

https://github.com/lpil/envoy/blob/e3c80ddf20b3fbb422eb4deba907268b32530692/src/envoy.gleam#L17

Erlang matches that: 

https://github.com/lpil/envoy/blob/e3c80ddf20b3fbb422eb4deba907268b32530692/src/envoy_ffi.erl#L7

JS has a string value rather than nil:

https://github.com/lpil/envoy/blob/e3c80ddf20b3fbb422eb4deba907268b32530692/src/envoy_ffi.mjs#L14

Neither one is favored in the tests as they both use the `_` match:

https://github.com/lpil/envoy/blob/e3c80ddf20b3fbb422eb4deba907268b32530692/test/envoy_test.gleam#L12

https://github.com/lpil/envoy/blob/e3c80ddf20b3fbb422eb4deba907268b32530692/test/envoy_test.gleam#L20

The `Result(String, Nil)` is probably the desired behavior as it matches `dict.get`:

https://github.com/gleam-lang/stdlib/blob/341a71049ad765f8788af497969efbb94aba0bab/src/gleam/dict.gleam#L152-L152

What do you think?

(Related to the test failure on the gleam cookbook: https://github.com/gleam-lang/cookbook/pull/20)

**Comment by lpil** [comment]
Oh how awful, I'm sorry about this!
